export const baishinData = [
 {
  id: '45378524',
  barilgaNer: 'Colloseum loft',
  price: '160$/night',
  zurag: 'https://a0.muscache.com/im/pictures/27d8a041-0e26-4172-8e04-c67c96dbe2d6.jpg?im_w=960',
  bedroom: '2 rooms, 3 beds',
  bathroom: 'shower 1',
  maxPeople: '4',
  floor: 6,
  turul: 'appartment',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '78275824',
  barilgaNer: 'Trastevere Flat',
  price: '120$/night',
  zurag: 'https://a0.muscache.com/im/pictures/miso/Hosting-43936026/original/a34872a2-9e48-4777-9612-4a55539356ae.jpeg?im_w=720',
  bedroom: '2 rooms, 4 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '5',
  floor: 3,
  turul: 'appartment',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '78254',
  barilgaNer: 'Villa Romana Loft',
  price: '140$/night',
  zurag: 'https://a0.muscache.com/im/pictures/76d0e5bf-5f45-4af1-a22b-b53bad8e5555.jpg?im_w=960',
  bedroom: '2 rooms, 2 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '6',
  floor: 8,
  turul: 'appartment',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '123475',
  barilgaNer: 'Villa Romana Loft',
  price: '140$/night',
  zurag: 'https://a0.muscache.com/im/pictures/76d0e5bf-5f45-4af1-a22b-b53bad8e5555.jpg?im_w=960',
  bedroom: '2 rooms, 2 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '6',
  floor: 8,
  turul: 'appartment',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '3657245',
  barilgaNer: 'House 1',
  price: '140$/night',
  zurag: 'https://a0.muscache.com/im/pictures/76d0e5bf-5f45-4af1-a22b-b53bad8e5555.jpg?im_w=960',
  bedroom: '2 rooms, 2 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '6',
  floor: 8,
  turul: 'house',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '275245',
  barilgaNer: 'House 2',
  price: '140$/night',
  zurag: 'https://a0.muscache.com/im/pictures/76d0e5bf-5f45-4af1-a22b-b53bad8e5555.jpg?im_w=960',
  bedroom: '2 rooms, 2 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '6',
  floor: 8,
  turul: 'house',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '98574',
  barilgaNer: 'Villa Romana Loft',
  price: '140$/night',
  zurag: 'https://a0.muscache.com/im/pictures/76d0e5bf-5f45-4af1-a22b-b53bad8e5555.jpg?im_w=960',
  bedroom: '2 rooms, 2 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '6',
  floor: 8,
  turul: 'appartment',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '524',
  barilgaNer: 'House 4',
  price: '140$/night',
  zurag: 'https://a0.muscache.com/im/pictures/76d0e5bf-5f45-4af1-a22b-b53bad8e5555.jpg?im_w=960',
  bedroom: '2 rooms, 2 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '6',
  floor: 8,
  turul: 'house',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '3524',
  barilgaNer: 'House 5',
  price: '140$/night',
  zurag: 'https://a0.muscache.com/im/pictures/76d0e5bf-5f45-4af1-a22b-b53bad8e5555.jpg?im_w=960',
  bedroom: '2 rooms, 2 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '6',
  floor: 8,
  turul: 'house',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '3965',
  barilgaNer: 'Villa Romana Loft',
  price: '140$/night',
  zurag: 'https://a0.muscache.com/im/pictures/76d0e5bf-5f45-4af1-a22b-b53bad8e5555.jpg?im_w=960',
  bedroom: '2 rooms, 2 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '6',
  floor: 8,
  turul: 'appartment',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '741',
  barilgaNer: 'House 6',
  price: '140$/night',
  zurag: 'https://a0.muscache.com/im/pictures/76d0e5bf-5f45-4af1-a22b-b53bad8e5555.jpg?im_w=960',
  bedroom: '2 rooms, 2 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '6',
  floor: 8,
  turul: 'house',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 },
 {
  id: '654',
  barilgaNer: 'House 7',
  price: '140$/night',
  zurag: 'https://a0.muscache.com/im/pictures/76d0e5bf-5f45-4af1-a22b-b53bad8e5555.jpg?im_w=960',
  bedroom: '2 rooms, 2 beds',
  bathroom: 'Bathtub: 1',
  maxPeople: '6',
  floor: 8,
  turul: 'house',
  checked: false,
  dining: 'yes',
  entertainment: 'home theater',
  outside: 'beach',
  foodArea: 'restaurant',
  meals: 'yes',
  location: 'Germany',
  amenities: 'soundproof, balcony',
 }
]